### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/pickles/train_data.pickle'

### ISSUE THREAD

**Issue by realchrisolin** [seiichiinoue/cnn-for-musical-onset-detection#6]
```
(venv) C:\Users\Chris Olin\PycharmProjects\onset_detection\cnn-for-musical-onset-detection>python train.py don
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    with open('./data/pickles/train_data.pickle', mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/pickles/train_data.pickle'
```

**Comment by seiichiinoue** [comment]
thank you for reporting the issue. 
you have reported that you cannot run `train.py` because of file not found error, but my environment, able to run script! 
before this issue, I fixed this code from
```
    with open('./data/pickles/train_reduced.pickle', mode='rb') as f:
        songs = pickle.load(f)
```
to below 
```
    try:
        with open('./data/pickles/train_data.pickle', mode='rb') as f: # train_data is big file so i cannot upload my sample data, but you can create training data set and locate here.
            songs = pickle.load(f)
    except FileNotFoundError:
        with open('./data/pickles/train_reduced.pickle', mode='rb') as f:
            songs = pickle.load(f)
```

still not working?

**Comment by realchrisolin** [comment]
unfortunately, no.

```
"C:\Users\Chris Olin\PycharmProjects\onset_detection\venv\Scripts\python.exe" "C:/Users/Chris Olin/PycharmProjects/onset_detection/cnn-for-musical-onset-detection/train.py" don
Traceback (most recent call last):
  File "C:/Users/Chris Olin/PycharmProjects/onset_detection/cnn-for-musical-onset-detection/train.py", line 15, in <module>
    with open('./data/pickles/train_data.pickle', mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/pickles/train_data.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Chris Olin/PycharmProjects/onset_detection/cnn-for-musical-onset-detection/train.py", line 19, in <module>
    songs = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

Process finished with exit code 1
```

is your local branch clean? I ask because on my end, there is no `train_data.pickle` file in `./data/pickles/`, but there is a `test_data.pickle` file. In either case, I can't tell if the `FileNotFoundError `isn't being excepted, or if I'm seeing it because it errored out immediately prior to the `_pickle.UnpicklingError`. Not sure what's causing the latter error.

Maybe we should compare environments/package versions?
```
(venv) C:\Users\Chris Olin\PycharmProjects\onset_detection>pip list
Package           Version
----------------- ----------
audioread         2.1.8
cffi              1.12.3
chainer           6.2.0
cycler            0.10.0
decorator         4.4.0
filelock          3.0.12
joblib            0.13.2
kiwisolver        1.1.0
librosa           0.7.0
llvmlite          0.29.0
matplotlib        3.1.1
numba             0.45.1
numpy             1.17.0
Pillow            6.1.0
pip               19.0.3
protobuf          3.7.1
pycparser         2.19
pylinktester      0.1
pyparsing         2.4.2
python-dateutil   2.8.0
PyYAML            5.1.2
resampy           0.2.2
scikit-learn      0.21.3
scipy             1.3.1
setuptools        40.8.0
six               1.12.0
sklearn           0.0
SoundFile         0.10.2
torch             1.2.0+cu92
torchvision       0.4.0+cu92
tqdm              4.34.0
typing            3.6.6
typing-extensions 3.6.6
```

**Comment by seiichiinoue** [comment]
i think this issue is related case.
https://github.com/DwangoMediaVillage/3dpose_gan/issues/1

**Comment by realchrisolin** [comment]
dunno what to tell you
```
(venv) C:\Users\Chris Olin\PycharmProjects\onset_detection\cnn-for-musical-onset-detection>git lfs install
Updated git hooks.
Git LFS initialized.
```
```

if __name__ == '__main__':

    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    net = convNet()
    net = net.to(device)

    with open('./data/pickles/train_reduced.pickle', mode='rb') as f:
        songs = pickle.load(f)
```

**Comment by seiichiinoue** [comment]
did you re-download target file(audio data) after installed git-lfs?

**Comment by realchrisolin** [comment]
sorry, I ended up with a concussion over a week ago and was under doctor's orders not to use any screens until today. what do you mean "re-download". `git pull`? I was under the impression the .pickle files in this repo are the target data.

**Comment by realchrisolin** [comment]
What do you mean by "re-download the target file"? Can you elaborate? I'm still stuck on this error.

**Comment by seiichiinoue** [comment]
sorry, its mean "downloading may have failed, so download the data again after install git-lfs"
did you downloaded git-lfs?

**Comment by realchrisolin** [comment]
you're not making any sense, unfortunately. Per my comment at https://github.com/seiichiinoue/cnn-for-musical-onset-detection/issues/6#issuecomment-523522913, I ran the `git lfs install` command and received the following output"

```
Updated git hooks.
Git LFS initialized.
```

You keep referring to "downloading" and "re-downloading" things, but that doesn't make any sense from my end. I'm not sure if it's a language barrier and something is getting lost in translation. All of the files I need should be in this repository. I don't know what else to download or what you mean when you say to "re-download the target file". The target file should already be in the repository. Can you please commit it if it hasn't been added?

**Comment by seiichiinoue** [comment]
im sorry for my mistake. i've downloaded this repo and tried to run for checking, but did not able to run.
I will upload part of the raw file later. Can you create audio data with command: `python music_processor.py train_reduced`? (I'll locate `reduced/` dir)

**Comment by seiichiinoue** [comment]
i uploaded new audio data. below is running sample 
```
$ python music_processor.py reduced
./data/train_reduced/365日の紙飛行機
./data/train_reduced/8OROCHI
./data/train_reduced/Abandoned Temple Final 2nd
./data/train_reduced/24karats TRIBE OF GOLD
$ python train.py don
/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
epoch: 1 running_loss: 3.0730985329
epoch: 2 running_loss: 2.7698714882
epoch: 3 running_loss: 2.6424603537
epoch: 4 running_loss: 2.7178966440
epoch: 5 running_loss: 2.7305703573
```
